const Types = {
    GET_DATA: 'GET_DATA',
    FAILED_GET_DATA: 'FAILED_GET_DATA',
    COMPLETE_GET_DATA: 'COMPLETE_GET_DATA',
    SET_LOADING: 'SET_LOADING',

    ADD_FORM_DATA: 'ADD_FORM_DATA',
    FAILED_ADD_FORM_DATA: 'FAILED_ADD_FORM_DATA',
    COMPLETE_ADD_FORM_DATA: 'COMPLETE_ADD_FORM_DATA',
    SET_FORM_DATA_LOADING: 'SET_FORM_DATA_LOADING',
}

export default Types;